# Generated by Django 2.0.2 on 2018-04-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0009_auto_20180405_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.Test'),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '칼럼'), (3, '커뮤니티'), (1, '소식')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(2, '중간'), (3, '어려움'), (1, '쉬움')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '개념확인형'), (2, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '추천고사'), (1, '일반'), (2, '진단고사')], null=True),
        ),
    ]
