# Generated by Django 2.0.2 on 2018-03-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerSrl', models.AutoField(primary_key=True, serialize=False)),
                ('a1', models.IntegerField(blank=True, null=True)),
                ('a2', models.IntegerField(blank=True, null=True)),
                ('a3', models.IntegerField(blank=True, null=True)),
                ('a4', models.IntegerField(blank=True, null=True)),
                ('a5', models.IntegerField(blank=True, null=True)),
                ('a6', models.IntegerField(blank=True, null=True)),
                ('a7', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoSrl', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(max_length=200, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemSrl', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(2, '수능형'), (4, '개념응용형'), (1, '내신형'), (3, '개념확인형')], null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(3, '어려움'), (2, '중간'), (1, '쉬움')], null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(blank=True, null=True, to='math_problem_app.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemUnit',
            fields=[
                ('problemUnitSrl', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(blank=True, choices=[(1, '수1'), (6, '기벡'), (5, '확통'), (2, '수2'), (4, '미적2'), (3, '미적1')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingSrl', models.AutoField(primary_key=True, serialize=False)),
                ('su1', models.IntegerField(blank=True, null=True)),
                ('su2', models.IntegerField(blank=True, null=True)),
                ('mi1', models.IntegerField(blank=True, null=True)),
                ('mi2', models.IntegerField(blank=True, null=True)),
                ('givec', models.IntegerField(blank=True, null=True)),
                ('hwaktong', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testSrl', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('problems', models.ManyToManyField(blank=True, null=True, to='math_problem_app.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userSrl', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(blank=True, null=True, to='math_problem_app.Answer')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.Rating')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.ProblemUnit'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.Test'),
        ),
    ]
