# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0002_auto_20180301_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingSrl', models.AutoField(primary_key=True, serialize=False)),
                ('su1', models.IntegerField(blank=True, null=True)),
                ('su2', models.IntegerField(blank=True, null=True)),
                ('mi1', models.IntegerField(blank=True, null=True)),
                ('mi2', models.IntegerField(blank=True, null=True)),
                ('givec', models.IntegerField(blank=True, null=True)),
                ('hwaktong', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 2, 14, 17, 51, 578869, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.Rating'),
        ),
    ]
