# Generated by Django 2.0.2 on 2018-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0005_auto_20180303_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='resource/photos/19cd8251-41a6-4d56-839c-2e650118669d'),
        ),
    ]
