# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0005_auto_20180303_1338'),
    ]

    operations = [
    ]
