# Generated by Django 2.0.2 on 2018-03-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0005_auto_20180329_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '칼럼'), (1, '소식'), (3, '커뮤니티')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answerType',
            field=models.IntegerField(blank=True, choices=[(2, '주관식'), (1, '객관식')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(3, '어려움'), (2, '중간'), (1, '쉬움')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '개념확인형'), (2, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '일반'), (3, '추천고사'), (2, '진단고사')], null=True),
        ),
    ]
