# Generated by Django 2.0.2 on 2018-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0006_auto_20180303_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemUnit',
            fields=[
                ('problemUnitSrl', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(blank=True, choices=[(1, '수1'), (3, '미적1'), (4, '미적2'), (2, '수2')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p7',
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(2, '중간'), (3, '어려움'), (1, '쉬움')], null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '수능형'), (1, '내신형'), (4, '개념응용형'), (3, '개념확인형')], null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.Problem'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='resource/photos/1faf917d-c360-41ce-93ac-1db058efe67a'),
        ),
        migrations.AddField(
            model_name='problem',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.ProblemUnit'),
        ),
    ]
