# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0006_auto_20180307_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='value',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='photo2',
        ),
        migrations.AddField(
            model_name='problem',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='resource/photos/471ff1fc-5cb8-4d6c-b36f-3a2bc02564ae'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(2, '중간'), (3, '어려움'), (1, '쉬움')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(2, '수2'), (1, '수1'), (5, '확통'), (3, '미적1'), (6, '기벡'), (4, '미적2')], null=True),
        ),
    ]
