# Generated by Django 2.0.2 on 2018-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0007_auto_20180309_1203'),
        ('math_problem_app', '0007_auto_20180307_1451'),
    ]

    operations = [
    ]
