# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0007_auto_20180309_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardSrl', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('viewCnt', models.IntegerField(blank=True, null=True)),
                ('recommendCnt', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(3, '진로'), (1, '소식'), (2, '칼럼')], null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '수능형'), (1, '내신형'), (3, '개념확인형'), (4, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, '수1'), (3, '미적1'), (5, '확통'), (2, '수2'), (6, '기벡'), (4, '미적2')], null=True),
        ),
    ]
