# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0008_auto_20180310_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='recommendCnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '칼럼'), (1, '소식'), (3, '진로')], null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='viewCnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '쉬움'), (3, '어려움'), (2, '중간')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '내신형'), (3, '개념확인형'), (4, '개념응용형'), (2, '수능형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, '수1'), (6, '기벡'), (3, '미적1'), (4, '미적2'), (2, '수2'), (5, '확통')], null=True),
        ),
    ]
