# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0009_auto_20180311_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='type',
        ),
        migrations.AddField(
            model_name='problem',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, '내신형'), (2, '수능형')], null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(2, '개념응용형'), (1, '개념확인형')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(3, '어려움'), (1, '쉬움'), (2, '중간')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(2, '수2'), (4, '미적2'), (3, '미적1'), (1, '수1'), (6, '기벡'), (5, '확통')], null=True),
        ),
    ]
