# Generated by Django 2.0.2 on 2018-03-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0009_auto_20180311_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '소식'), (2, '칼럼'), (3, '진로')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(3, '어려움'), (1, '쉬움'), (2, '중간')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '개념확인형'), (2, '수능형'), (4, '개념응용형'), (1, '내신형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(5, '확통'), (3, '미적1'), (4, '미적2'), (2, '수2'), (1, '수1'), (6, '기벡')], null=True),
        ),
    ]
