# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0010_auto_20180311_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerNum',
            fields=[
                ('answerNumSrl', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a7',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '일반'), (2, '진단고사')], null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '소식'), (3, '진로'), (2, '칼럼')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '쉬움'), (3, '어려움'), (2, '중간')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(2, '수2'), (3, '미적1'), (6, '기벡'), (4, '미적2'), (1, '수1'), (5, '확통')], null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='math_problem_app.AnswerNum'),
        ),
    ]
