# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0012_auto_20180311_1832'),
    ]

    operations = [
    ]
