# Generated by Django 2.0.2 on 2018-03-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0013_auto_20180311_0312'),
        ('math_problem_app', '0012_auto_20180311_1832'),
    ]

    operations = [
    ]
