# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0014_auto_20180312_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentSrl', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '쉬움'), (2, '중간'), (3, '어려움')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '개념확인형'), (2, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(2, '수2'), (4, '미적2'), (6, '기벡'), (3, '미적1'), (1, '수1'), (5, '확통')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '일반'), (2, '진단고사')], null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.Comment'),
        ),
    ]
