# Generated by Django 2.0.2 on 2018-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0015_auto_20180312_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explanation',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '개념확인형'), (2, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(6, '기벡'), (5, '확통'), (1, '수1'), (4, '미적2'), (3, '미적1'), (2, '수2')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '진단고사'), (1, '일반')], null=True),
        ),
    ]
