# Generated by Django 2.0.2 on 2018-03-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0015_auto_20180313_2127'),
        ('math_problem_app', '0016_auto_20180312_0036'),
    ]

    operations = [
    ]
