# Generated by Django 2.0.2 on 2018-03-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0018_auto_20180314_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '칼럼'), (3, '커뮤니티'), (1, '소식')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '쉬움'), (3, '어려움'), (2, '중간')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, '내신형'), (2, '수능형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, '수1'), (4, '미적2'), (3, '미적1'), (5, '확통'), (2, '수2'), (6, '기벡')], null=True),
        ),
    ]
