# Generated by Django 2.0.2 on 2018-03-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0017_auto_20180315_2308'),
        ('math_problem_app', '0019_auto_20180314_0106'),
    ]

    operations = [
    ]
