# Generated by Django 2.0.2 on 2018-03-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0021_auto_20180315_2339'),
        ('math_problem_app', '0018_auto_20180317_1756'),
    ]

    operations = [
    ]
