# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0022_auto_20180319_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemMiddleUnit',
            fields=[
                ('problemMiddleUnitSrl', models.AutoField(primary_key=True, serialize=False)),
                ('middleUnit', models.IntegerField(blank=True, choices=[(17, '확률'), (16, '순열과 조합'), (18, '통계'), (19, '이차곡선'), (6, '수열'), (21, '공간도형과 공간좌표'), (20, '평면벡터'), (4, '집합과 명제'), (2, '방정식과 부등식'), (8, '수열의 극한'), (12, '지수함수와 로그함수'), (7, '지수와 로그'), (9, '함수의 극한'), (13, '삼각함수'), (15, '적분법'), (1, '다항식'), (3, '도형의 방정식'), (10, '다항함수의 미분법'), (14, '미분법'), (22, '공간벡터'), (5, '함수'), (11, '다항함수의 적분법')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSmallUnit',
            fields=[
                ('problemSmallUnitSrl', models.AutoField(primary_key=True, serialize=False)),
                ('smallUnit', models.IntegerField(blank=True, choices=[(17, '확률'), (16, '순열과 조합'), (18, '통계'), (19, '이차곡선'), (6, '수열'), (21, '공간도형과 공간좌표'), (20, '평면벡터'), (4, '집합과 명제'), (2, '방정식과 부등식'), (8, '수열의 극한'), (12, '지수함수와 로그함수'), (7, '지수와 로그'), (9, '함수의 극한'), (13, '삼각함수'), (15, '적분법'), (1, '다항식'), (3, '도형의 방정식'), (10, '다항함수의 미분법'), (14, '미분법'), (22, '공간벡터'), (5, '함수'), (11, '다항함수의 적분법')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '칼럼'), (1, '소식'), (3, '커뮤니티')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answerType',
            field=models.IntegerField(blank=True, choices=[(2, '주관식'), (1, '객관식')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(2, '수능형'), (1, '내신형')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(2, '개념응용형'), (1, '개념확인형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(6, '기벡'), (5, '확통'), (3, '미적1'), (1, '수1'), (2, '수2'), (4, '미적2')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '일반'), (2, '진단고사'), (3, '추천고사')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1학년'), (2, '2학년'), (3, '3학년')], null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='middleUnit',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.ProblemMiddleUnit'),
        ),
        migrations.AddField(
            model_name='problem',
            name='smallUnit',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.ProblemSmallUnit'),
        ),
    ]
