# Generated by Django 2.0.2 on 2018-03-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0021_auto_20180318_2233'),
        ('math_problem_app', '0023_auto_20180317_2342'),
    ]

    operations = [
    ]
