# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0024_auto_20180328_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '소식'), (3, '커뮤니티'), (2, '칼럼')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answerType',
            field=models.IntegerField(blank=True, choices=[(1, '객관식'), (2, '주관식')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(2, '중간'), (3, '어려움'), (1, '쉬움')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '개념확인형'), (2, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemmiddleunit',
            name='middleUnit',
            field=models.IntegerField(blank=True, choices=[(3, '도형의 방정식'), (14, '미분법'), (11, '다항함수의 적분법'), (5, '함수'), (6, '수열'), (19, '이차곡선'), (7, '지수와 로그'), (21, '공간도형과 공간좌표'), (2, '방정식과 부등식'), (20, '평면벡터'), (4, '집합과 명제'), (10, '다항함수의 미분법'), (12, '지수함수와 로그함수'), (1, '다항식'), (8, '수열의 극한'), (13, '삼각함수'), (15, '적분법'), (22, '공간벡터'), (16, '순열과 조합'), (9, '함수의 극한'), (17, '확률'), (18, '통계')], null=True),
        ),
        migrations.AlterField(
            model_name='problemsmallunit',
            name='smallUnit',
            field=models.IntegerField(blank=True, choices=[(37, '여러가지 함수의 미분법'), (5, '이차방정식과 이차함수'), (50, '평면벡터의 뜻'), (53, '공간좌표'), (23, '수열의 극한'), (16, '함수'), (42, '순열과 조합'), (45, '조건부 확률'), (24, '급수'), (11, '도형의 이동'), (10, '원의 방정식'), (30, '정적분'), (33, '지수함수와 로그함수의 미분'), (8, '평면좌표'), (38, '도함수의 활용'), (52, '공간도형'), (41, '경우의 수'), (1, '다항식의 연산'), (9, '직선의 방정식'), (32, '지수함수와 로그함수의 뜻과 그래프'), (35, '삼각함수의 그래프'), (26, '함수의 연속'), (12, '부등식의 영역'), (40, '정적분의 활용'), (47, '통계적 추정'), (39, '여러가지 함수의 적분법'), (28, '도함수의 활용'), (13, '집합'), (29, '부정적분'), (51, '평면운동'), (19, '등차수열과 등비수열'), (54, '공간벡터'), (20, '여러가지 수열'), (36, '삼각함수의 미분'), (46, '확률변수와 확률분포'), (27, '미분계수와 도함수'), (17, '유리식과 유리함수'), (2, '항등식과 나머지 정리'), (7, '여러가지 부등식'), (14, '명제'), (49, '이차곡선과 접선의 방정식'), (43, '이항정리'), (31, '정적분의 활용'), (4, '복소수와 이차방정식'), (25, '함수의 극한'), (34, '삼각함수의 뜻'), (44, '확률의 뜻'), (6, '여러가지 방정식'), (48, '이차곡선의 방정식'), (3, '인수분해'), (18, '무리식과 무리함수'), (21, '지수와 로그'), (22, '상용로그'), (15, '절대부등식')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(2, '수2'), (5, '확통'), (3, '미적1'), (6, '기벡'), (1, '수1'), (4, '미적2')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '추천고사'), (2, '진단고사'), (1, '일반')], null=True),
        ),
    ]
