# Generated by Django 2.0.2 on 2018-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0026_auto_20180318_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tests',
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(3, '어려움'), (2, '중간'), (1, '쉬움')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(2, '개념응용형'), (1, '개념확인형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, '수1'), (4, '미적2'), (5, '확통'), (3, '미적1'), (6, '기벡'), (2, '수2')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(3, '3학년'), (1, '1학년'), (2, '2학년')], null=True),
        ),
    ]
