# Generated by Django 2.0.2 on 2018-03-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0023_auto_20180326_0024'),
        ('math_problem_app', '0027_auto_20180319_2020'),
    ]

    operations = [
    ]
