# Generated by Django 2.0.2 on 2018-03-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0028_merge_20180327_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recommendSrl', models.AutoField(primary_key=True, serialize=False)),
                ('aimGrade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '커뮤니티'), (1, '소식'), (2, '칼럼')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answerType',
            field=models.IntegerField(blank=True, choices=[(1, '객관식'), (2, '주관식')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(2, '중간'), (3, '어려움'), (1, '쉬움')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '개념확인형'), (2, '개념응용형')], null=True),
        ),
        migrations.AlterField(
            model_name='problemmiddleunit',
            name='middleUnit',
            field=models.IntegerField(blank=True, choices=[(7, '지수와 로그'), (21, '공간도형과 공간좌표'), (1, '다항식'), (2, '방정식과 부등식'), (12, '지수함수와 로그함수'), (8, '수열의 극한'), (11, '다항함수의 적분법'), (19, '이차곡선'), (6, '수열'), (15, '적분법'), (9, '함수의 극한'), (16, '순열과 조합'), (10, '다항함수의 미분법'), (18, '통계'), (3, '도형의 방정식'), (4, '집합과 명제'), (22, '공간벡터'), (14, '미분법'), (13, '삼각함수'), (17, '확률'), (20, '평면벡터'), (5, '함수')], null=True),
        ),
        migrations.AlterField(
            model_name='problemsmallunit',
            name='smallUnit',
            field=models.IntegerField(blank=True, choices=[(24, '급수'), (33, '지수함수와 로그함수의 미분'), (43, '이항정리'), (27, '미분계수와 도함수'), (5, '이차방정식과 이차함수'), (49, '이차곡선과 접선의 방정식'), (7, '여러가지 부등식'), (35, '삼각함수의 그래프'), (45, '조건부 확률'), (48, '이차곡선의 방정식'), (29, '부정적분'), (52, '공간도형'), (14, '명제'), (44, '확률의 뜻'), (31, '정적분의 활용'), (36, '삼각함수의 미분'), (41, '경우의 수'), (46, '확률변수와 확률분포'), (26, '함수의 연속'), (40, '정적분의 활용'), (38, '도함수의 활용'), (11, '도형의 이동'), (22, '상용로그'), (1, '다항식의 연산'), (12, '부등식의 영역'), (54, '공간벡터'), (23, '수열의 극한'), (10, '원의 방정식'), (15, '절대부등식'), (16, '함수'), (34, '삼각함수의 뜻'), (53, '공간좌표'), (3, '인수분해'), (50, '평면벡터의 뜻'), (25, '함수의 극한'), (51, '평면운동'), (8, '평면좌표'), (20, '여러가지 수열'), (28, '도함수의 활용'), (37, '여러가지 함수의 미분법'), (39, '여러가지 함수의 적분법'), (6, '여러가지 방정식'), (2, '항등식과 나머지 정리'), (9, '직선의 방정식'), (19, '등차수열과 등비수열'), (18, '무리식과 무리함수'), (47, '통계적 추정'), (42, '순열과 조합'), (13, '집합'), (21, '지수와 로그'), (30, '정적분'), (17, '유리식과 유리함수'), (4, '복소수와 이차방정식'), (32, '지수함수와 로그함수의 뜻과 그래프')], null=True),
        ),
        migrations.AlterField(
            model_name='problemunit',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(4, '미적2'), (5, '확통'), (1, '수1'), (2, '수2'), (3, '미적1'), (6, '기벡')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '추천고사'), (2, '진단고사'), (1, '일반')], null=True),
        ),
        migrations.AddField(
            model_name='recommend',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.ProblemUnit'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommend',
            field=models.ManyToManyField(blank=True, null=True, to='math_problem_app.Recommend'),
        ),
    ]
