# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0028_auto_20180402_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='math_problem_app.Photo'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answerType',
            field=models.IntegerField(blank=True, choices=[(1, '객관식'), (2, '주관식')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(2, '중간'), (1, '쉬움'), (3, '어려움')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, '진단고사'), (1, '일반'), (3, '추천고사')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(3, '3학년'), (1, '1학년'), (2, '2학년')], null=True),
        ),
    ]
