# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_problem_app', '0032_auto_20180409_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '커뮤니티'), (2, '칼럼'), (1, '소식')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answerType',
            field=models.IntegerField(blank=True, choices=[(1, '객관식'), (2, '주관식')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '쉬움'), (3, '어려움'), (2, '중간')], null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, '내신형'), (2, '수능형')], null=True),
        ),
        migrations.AlterField(
            model_name='studydate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, '추천고사'), (2, '진단고사'), (1, '일반')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(3, '3학년'), (1, '1학년'), (2, '2학년')], null=True),
        ),
    ]
